webapp/main/routes.py
from flask import render_template
from flask import Blueprint

main = Blueprint('main', __name__)


@main.route("/homepage")
def homepage():
    return render_template('helloworld/homepage.html')

@main.route("/")
@main.route("/pop_up")
def pop_up():
    return render_template('helloworld/pop-up.html')


@main.route("/skim")
def skim():
    return render_template('helloworld/skim.html')


@main.route("/one")
def one():
    return render_template('helloworld/one.html')


@main.route("/twoA")
def twoA():
    return render_template('helloworld/twoA.html')


@main.route("/twoB")
def twoB():
    return render_template('helloworld/twoB.html')


@main.route("/threeA")
def threeA():
    return render_template('helloworld/threeA.html')


@main.route("/threeB")
def threeB():
    return render_template('helloworld/threeB.html')


@main.route("/fourB")
def fourB():
    return render_template('helloworld/fourB.html')


@main.route("/fiveB")
def fiveB():
    return render_template('helloworld/fiveB.html')


@main.route("/sixB")
def sixB():
    return render_template('helloworld/sixB.html')


@main.route("/seven")
def seven():
    return render_template('helloworld/seven.html')


@main.route("/eight")
def eight():
    return render_template('helloworld/eight.html')

webapp/templates/helloworld/eight.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: #0000FF;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: #0000FF;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://media.giphy.com/media/9FXvErYPCSB54Eb2pM/giphy.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.homepage') }}" >AGREE AND PROCEED TO WEBSITE</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/fiveB.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: black;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: black;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/5b629cdd4f3d0de4008329b4f81e9da8/tumblr_piypluarU51swralzo4_r1_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.sixB') }}" >OK</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/fourB.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: white;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #0000FF;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: white;
      color: #0000FF;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/ce2883bf27a44e4d3bdcecbe46f510d4/tumblr_piypluarU51swralzo5_r1_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.fiveB') }}" >OK</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/one.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: black;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: black;
      color: #FFF808;
    }

</style>
<IMG id="gif" SRC="https://66.media.tumblr.com/19a099b1d8991c2a319c4b76ba14743c/tumblr_piypfoQRs71swralzo7_400.gif" ALT="Skim">
  <br><br><br><br>
  <center>
<a class="button" href="{{ url_for('main.twoA') }}" >YES</a>&nbsp;&nbsp;
<a class="button" href="{{ url_for('main.twoB') }}" >NO</a>&nbsp;&nbsp;
</center>
</body>

webapp/templates/helloworld/pop-up.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
  <style>
  body {
    margin: 0 0;
    background-color: #FFF808;

}

#title {
      z-index: 3;
      max-width: 200px;
      padding-top: 70px;
      padding-left: 60px;

}
  .text {
      padding-top: 70px;
      padding-right: 70px;
      float: right;
      text-align: left;
      font-family: "futura";
      width: 70vw;
      color: black;
      text-decoration: none;
      padding-bottom: 70px;
      font-size: calc(14px + (21 - 15) * ((100vw - 300px) / (1600 - 300)));
      line-height: calc(1.5em + (1.5 - 1.2) * ((100vw - 300px)/(1600 - 300)));
}

h2 {
  padding: 1vw;
  font-size: calc(25px + (25 - 13) * ((100vw - 300px) / (1600 - 300)));
  font-family: "futura";
}

.button {
    background-color: black; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    font-family: "futura";
    font-size: 15pt;
    font-size: calc(14px + (21 - 15) * ((100vw - 300px) / (1600 - 300)));

}
.button:hover{
  background-color: black;
  color: #FFF808;
}

h2 {
  padding: 1vw;
}

p {
  font-family: "futura";
}

.popup {
  position: fixed;
  padding: 30px;
  width: 50vw;
  left: 45%;
  margin-left: -25vw;
  top: 30%;
  margin-top: -90px;
  background: black;
  z-index: 20;
  font-size: 15px;
}

#popup1 {
  -webkit-box-shadow: 0px 0px 0px 9999px rgba(0, 0, 0, 0.5);
  box-shadow: 0px 0px 0px 9999px rgba(0, 0, 0, 0.5);
}

#popup2:after {
  position: fixed;
  content: "";
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.5);
  z-index: -2;
}

#popup2:before {
  position: absolute;
  content: "";
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  background: #FFF;
  z-index: -1;
}

.blabla {
  font-size: 15px;
  color: black;
  font-family: futura;
}

.blabla:hover {
  color: blue;
  text-decoration: underline;
}

  </style>
  <div class="popup" id="popup2">
    <center>

      <h2>WE CARE ABOUT YOUR PRIVACY</h2>
    </center>
    <p>We have recently updated our Terms and Conditions. Please select  an option below to continue to our website.</p>
      <br><br>
    <center>
    <a class="button" href="{{ url_for('main.skim') }}" >Proceed to Terms and Conditions</a></center>
    <br>
  </div>
  <IMG id="title" SRC="https://66.media.tumblr.com/cb27d14c5cbed21a26ac96991ac06ad4/tumblr_piypluarU51swralzo6_r1_1280.png" ALT="Skim">
<div class="text">
  <h2>Welcome to SKIM</h2>
  Welcome and Congratulations, you’ve successfully made it!
  <br><br>
We are SKIM and our project focuses on how dazzling it can be to blindly accept Terms and Conditions and Privacy Policies. These terms and policies are more often than not written in legal English, making it difficult to understand even if carefully read. Furthermore, due to the amount of information that is supplied, we could miss out important paragraphs. This makes it easy for us to fall for scams as companies try to dazzle dangerous terms and clauses within their Ts&Cs and PPs taking advantage of your personal information and data.
<br><br>
In fact, you may have even missed our hidden ‘a’ in our logo as you might just have ‘SKIM-ed that as well, revealing our second name SKAM.
<br><br>
As the nature of this is quite complex, we have come up with our own graphic language, including colorful animations that dazzle you from the already dazzling Ts&Cs.
By using vibrant colors such as our yellow, we draw inspiration from warning signs that try to grab your attention. We need your attention – not only to understand our narrative within our animations but also because we would like to show you how dangerous it can be to blindly accept everything and how little effort we give to ‘understand’ such an important piece of information about our data protection.
<br><br>
  </body>
</div>
</html>

webapp/templates/helloworld/seven.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: #0000FF;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: #0000FF;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/e29d7d2d7b1aafcc7d4a119dae72b911/tumblr_piypluarU51swralzo7_r1_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.eight') }}" >LEARN MORE</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/sixB.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: #0000FF;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: #0000FF;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/4b1c7f1f218a47bb0c11aec944eebaa6/tumblr_piypluarU51swralzo2_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.seven') }}" >LEARN MORE</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/skim.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: #FFF808;

}

#title {
      z-index: 3;
      max-width: 200px;
      padding-top: 70px;
      padding-left: 60px;

}
  .text {
      padding-top: 70px;
      padding-right: 70px;
      float: right;
      text-align: left;
      font-family: "futura";
      width: 70vw;
      color: black;
      text-decoration: none;
      padding-bottom: 70px;
      font-size: calc(14px + (21 - 15) * ((100vw - 300px) / (1600 - 300)));
      line-height: calc(1.5em + (1.5 - 1.2) * ((100vw - 300px)/(1600 - 300)));
}
.button {
    background-color: black; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    font-family: "futura";

}
.button:hover{
  background-color: black;
  color: #FFF808;
}

h2 {
  padding: 1vw;
  font-size: 23pt;
  font-family: "futura";
  line-height: 23pt; 
}

  </style>
  <IMG id="title" SRC="https://66.media.tumblr.com/cb27d14c5cbed21a26ac96991ac06ad4/tumblr_piypluarU51swralzo6_r1_1280.png" ALT="Skim">
<div class="text">
  <h2>Welcome to SKIM</h2>
  	<p>These terms and conditions outline the rules and regulations for the use of SKIM's Website.</p> <br />
  	<span style="text-transform: capitalize;"> SKIM</span> is located at:<br />
  	<address>45-65 Peckham Road , London<br />England - SE13 7LL, London<br />
  	</address>
  	<p>By accessing this website we assume you accept these terms and conditions in full. Do not continue to use SKIM's website
  	if you do not accept all of the terms and conditions stated on this page.</p>
  	<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice
  	and any or all Agreements: “Client”, “You” and “Your” refers to you, the person accessing this website
  	and accepting the Company’s terms and conditions. “The Company”, “Ourselves”, “We”, “Our” and “Us”, refers
  	to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves, or either the Client
  	or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake
  	the process of our assistance to the Client in the most appropriate manner, whether by formal meetings
  	of a fixed duration, or any other means, for the express purpose of meeting the Client’s needs in respect
  	of provision of the Company’s stated services/products, in accordance with and subject to, prevailing law
  	of London. Any use of the above terminology or other words in the singular, plural,
  	capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p><h2>Cookies</h2>
  	<p>We employ the use of cookies. By using SKIM's website you consent to the use of cookies
  	in accordance with SKIM’s privacy policy.</p><p>Most of the modern day interactive web sites
  	use cookies to enable us to retrieve user details for each visit. Cookies are used in some areas of our site
  	to enable the functionality of this area and ease of use for those people visiting. Some of our
  	affiliate / advertising partners may also use cookies.</p><h2>License</h2>
  	<p>Unless otherwise stated, SKIM and/or it’s licensors own the intellectual property rights for
  	all material on SKIM. All intellectual property rights are reserved. You may view and/or print
  	pages from http://www.sk1m.me for your own personal use subject to restrictions set in these terms and conditions.</p>
  	<p>You must not:</p>
  	<ol>
  		<li>Republish material from http://www.sk1m.me</li>
  		<li>Sell, rent or sub-license material from http://www.sk1m.me</li>
  		<li>Reproduce, duplicate or copy material from http://www.sk1m.me</li>
  	</ol>
  	<p>Redistribute content from SKIM (unless content is specifically made for redistribution).</p>
  <h2>Hyperlinking to our Content</h2>
  	<ol>
  		<li>The following organizations may link to our Web site without prior written approval:
  			<ol>
  			<li>Government agencies;</li>
  			<li>Search engines;</li>
  			<li>News organizations;</li>
  			<li>Online directory distributors when they list us in the directory may link to our Web site in the same
  				manner as they hyperlink to the Web sites of other listed businesses; and</li>
  			<li>Systemwide Accredited Businesses except soliciting non-profit organizations, charity shopping malls,
  				and charity fundraising groups which may not hyperlink to our Web site.</li>
  			</ol>
  		</li>
  	</ol>
  	<ol start="2">
  		<li>These organizations may link to our home page, to publications or to other Web site information so long
  			as the link: (a) is not in any way misleading; (b) does not falsely imply sponsorship, endorsement or
  			approval of the linking party and its products or services; and (c) fits within the context of the linking
  			party's site.
  		</li>
  		<li>We may consider and approve in our sole discretion other link requests from the following types of organizations:
  			<ol>
  				<li>commonly-known consumer and/or business information sources such as Chambers of Commerce, American
  					Automobile Association, AARP and Consumers Union;</li>
  				<li>dot.com community sites;</li>
  				<li>associations or other groups representing charities, including charity giving sites,</li>
  				<li>online directory distributors;</li>
  				<li>internet portals;</li>
  				<li>accounting, law and consulting firms whose primary clients are businesses; and</li>
  				<li>educational institutions and trade associations.</li>
  			</ol>
  		</li>
  	</ol>
  	<p>We will approve link requests from these organizations if we determine that: (a) the link would not reflect
  	unfavorably on us or our accredited businesses (for example, trade associations or other organizations
  	representing inherently suspect types of business, such as work-at-home opportunities, shall not be allowed
  	to link); (b)the organization does not have an unsatisfactory record with us; (c) the benefit to us from
  	the visibility associated with the hyperlink outweighs the absence of <?=$companyName?>; and (d) where the
  	link is in the context of general resource information or is otherwise consistent with editorial content
  	in a newsletter or similar product furthering the mission of the organization. By using our service, you agree to give up all use of your personal devices.</p>

  	<p>These organizations may link to our home page, to publications or to other Web site information so long as
  	the link: (a) is not in any way misleading; (b) does not falsely imply sponsorship, endorsement or approval
  	of the linking party and it products or services; and (c) fits within the context of the linking party's
  	site.</p>

  	<p>If you are among the organizations listed in paragraph 2 above and are interested in linking to our website,
  	you must notify us by sending an e-mail to <a href="mailto:info@sk1m.me" title="send an email to info@sk1m.me">info@sk1m.me</a>.
  	Please include your name, your organization name, contact information (such as a phone number and/or e-mail
  	address) as well as the URL of your site, a list of any URLs from which you intend to link to our Web site,
  	and a list of the URL(s) on our site to which you would like to link. Allow 2-3 weeks for a response.</p>

  	<p>Approved organizations may hyperlink to our Web site as follows:</p>

  	<ol>
  		<li>By use of our corporate name; or</li>
  		<li>By use of the uniform resource locator (Web address) being linked to; or</li>
  		<li>By use of any other description of our Web site or material being linked to that makes sense within the
  			context and format of content on the linking party's site.</li>
  	</ol>
  	<p>No use of SKIM’s logo or other artwork will be allowed for linking absent a trademark license
  	agreement.</p>
  <h2>Iframes</h2>
  	<p>Without prior approval and express written permission, you may not create frames around our Web pages or
  	use other techniques that alter in any way the visual presentation or appearance of our Web site.</p>
  <h2>Reservation of Rights</h2>
  	<p>We reserve the right at any time and in its sole discretion to request that you remove all links or any particular
  	link to our Web site. You agree to immediately remove all links to our Web site upon such request. We also
  	reserve the right to amend these terms and conditions and its linking policy at any time. By continuing
  	to link to our Web site, you agree to be bound to and abide by these linking terms and conditions.</p>
  <h2>Removal of links from our website</h2>
  	<p>If you find any link on our Web site or any linked web site objectionable for any reason, you may contact
  	us about this. We will consider requests to remove links but will have no obligation to do so or to respond
  	directly to you.</p>
  	<p>Whilst we endeavour to ensure that the information on this website is correct, we do not warrant its completeness
  	or accuracy; nor do we commit to ensuring that the website remains available or that the material on the
  	website is kept up to date.</p>
  <h2>Content Liability</h2>
  	<p>We shall have no responsibility or liability for any content appearing on your Web site. You agree to indemnify
  	and defend us against all claims arising out of or based upon your Website. No link(s) may appear on any
  	page on your Web site or within any context containing content or materials that may be interpreted as
  	libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or
  	other violation of, any third party rights.</p>
  <h2>Disclaimer</h2>
  	<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill). Nothing in this disclaimer will:</p>
  	<ol>
  	<li>limit or exclude our or your liability for death or personal injury resulting from negligence;</li>
  	<li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
  	<li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
  	<li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
  	</ol>
  	<p>The limitations and exclusions of liability set out in this Section and elsewhere in this disclaimer: (a)
  	are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer or
  	in relation to the subject matter of this disclaimer, including liabilities arising in contract, in tort
  	(including negligence) and for breach of statutory duty.</p>
  	<p>To the extent that the website and the information and services on the website are provided free of charge,
  	we will not be liable for any loss or damage of any nature.</p>
    <br>
<a class="button" href="{{ url_for('main.one') }}" >I have read and agree to the Terms</a></div>
</div>
  </body>
</div>
</html>

webapp/templates/helloworld/threeA.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: black;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: black;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/a8871bf0794422a00620b98c394fc98a/tumblr_piypfoQRs71swralzo10_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.seven') }}" >YES</a>
  <a class="button" href="{{ url_for('main.fiveB') }}" >WHAT?</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/threeB.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: black;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: black;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/c050fa29fbb4cb587d13f8e649e647d5/tumblr_piypfoQRs71swralzo5_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.fourB') }}" >OPEN</a>
</body>

webapp/templates/helloworld/twoA.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: black;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: #FFF808;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: black;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/ca403ef54d975dcf0609692a292ebe0a/tumblr_piypfoQRs71swralzo9_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.threeA') }}" >YES</a>
  <a class="button" href="{{ url_for('main.fiveB') }}" >NO</a>
  </center>
  <br>
</body>

webapp/templates/helloworld/twoB.html
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Terms of Service</title>
  </head>
  <body>
  <style>
  body, * {
    margin: 0 0;
    background-color: #FFF808;
}
#gif{
      width: 100%;

    }
    .button {
        background-color: black;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        font-family: "futura";

    }
    .button:hover{
      background-color: black;
      color: #FFF808;
      }

  </style>
  <IMG id="gif" SRC="https://66.media.tumblr.com/ea08fa34c3e2ceff74df603bce087412/tumblr_piypfoQRs71swralzo6_1280.gif" ALT="Skim">
    <br><br><br><br>
    <center>
  <a class="button" href="{{ url_for('main.threeB') }}" >CONTINUE</a>
</body>